name: save_disaster
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  lottie: ^2.6.0

  #CORE
  equatable: ^2.0.5
  envied: ^0.5.3
  #UTILITIES
  kartal: ^3.5.0
  cached_network_image: ^3.3.1
  #NAVIGATION
  auto_route: ^7.8.4
  #CACHE
  shared_preferences: ^2.2.2

  #LOCATION
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  #SERVICE
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  http: ^1.2.0

  #WEBVIEW
  url_launcher: ^6.2.4
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.1
  auto_route_generator: ^7.3.2
  envied_generator: ^0.5.3
flutter_gen:
  output: lib/product/gen
  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs:
      - assets/colors/color.xml
flutter:
  uses-material-design: true

  assets:
    - assets/colors/
    - assets/lottie/
    - assets/icons/
    - assets/images/
