// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, public_member_api_docs
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
import 'package:save_disaster/product/config/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Env.firebaseWebApiKey,
    appId: '1:275081898844:web:9ddfc6921882f8fcc66f99',
    messagingSenderId: '275081898844',
    projectId: 'save-disaster',
    authDomain: 'save-disaster.firebaseapp.com',
    storageBucket: 'save-disaster.appspot.com',
    measurementId: 'G-PBKTY4WSB6',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Env.firebaseAndroidApiKey,
    appId: '1:275081898844:android:d330620f74a09b08c66f99',
    messagingSenderId: '275081898844',
    projectId: 'save-disaster',
    storageBucket: 'save-disaster.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.firebaseIOSApiKey,
    appId: '1:275081898844:ios:94386fe11a93c336c66f99',
    messagingSenderId: '275081898844',
    projectId: 'save-disaster',
    storageBucket: 'save-disaster.appspot.com',
    iosBundleId: 'com.example.saveDisaster',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.firebaseMacOSApiKey,
    appId: '1:275081898844:ios:6e738b31b11e453bc66f99',
    messagingSenderId: '275081898844',
    projectId: 'save-disaster',
    storageBucket: 'save-disaster.appspot.com',
    iosBundleId: 'com.example.saveDisaster.RunnerTests',
  );
}
